---
title: "NY HUCP Utilization Services Summary"
date: "`r format(Sys.time(), '%B %d %Y')`"
output: pdf_document
header-inlcudes:
    - usepackage{amsmath}
    - usepackage[document]{ragged2e}
---


```{r rmd_setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(include=FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=TRUE)
knitr::opts_knit$set(root.dir='..')
```
```{r libraries}
library(haven)
library(tidyverse)
library(knitr)
library(kableExtra)
library(RColorBrewer)
```

```{r plot settings}
theme_set(theme_bw())
```

```{r functions}
printKable <- function(tbl_data, caption='') {
	# Print kable of utilization x payer data

		kable(tbl_temp, digits=2, caption=paste0('Payer types by service utilization, ', year), col.names=names(tbl_temp), format='latex', booktabs=TRUE, longtable=TRUE) %>%
		kable_styling(latex_options=c('hold_position', 'striped', 'repeat_header'))
		
}
```

```{r data}
# Utilization by payer type
dat_pay <- read_dta('dump/ny_sid_supp_pay.dta')
# Payer type by utilization services
dat_util <- read_dta('dump/ny_sid_supp_util.dta')
# Utilization by household income quartiles
dat_inc <- read_dta('dump/ny_sid_supp_inc.dta')
```


# Share of service utilization by payer type

- *Note:* rows sum to 1.00

```{r prep pay}
vars <- names(dat_pay)[grep('_pc$', names(dat_pay))]

temp_pay <- dat_pay %>%
	select(year, pay1, !!vars) %>%
	mutate(
		payer=case_when(
			pay1==1 ~ 'Medicare',
			pay1==2 ~ 'Medicaid',
			pay1==3 ~ 'Private ins.',
			pay1==4 ~ 'Self-pay',
			pay1==5 ~ 'No charge',
			pay1==6 ~ 'Other'),
		) %>%
	arrange(year, pay1) %>%
	select(year, payer, !!vars)

years <- 2006:2012
# Format each year into separate table
pay_years <- lapply(years, function(y, .data=temp_pay, .vars=vars) {
	.temp <- .data %>%
		filter(year==!!y) %>%
		select(payer, !!.vars) %>%
		t()

	# Grep col & row names
	payer_types <- .temp[1,]
	services <- sub('_pc$', '', row.names(.temp[-1,]))
	# Cast to tibble
	.temp <- .temp[-1,] %>% as_tibble(rownames=NA)
	# Set col names
	names(.temp) <- payer_types
	# Convert percentages to numeric
	.temp <- mutate_all(.temp, .funs=as.numeric)
	# Add utilization services
	.temp <- mutate(.temp, service=!!services) %>%
		select(service, everything())

	return(.temp)
})
names(pay_years) <- years
```

```{r print pay, include=TRUE, results='asis'}
for (year in years) {
	tbl_temp <- pay_years[[!!year]]
	
	print(kable(tbl_temp, digits=2, caption=paste0('Service utilization by payer type, ', year), col.names=names(tbl_temp), format='latex', booktabs=TRUE) %>%
	kable_styling(latex_options=c('hold_position', 'striped')))
}
```


# Share of payer types by service utilization

- *Note:* rows sum to 1.0

```{r prep util}
vars <- names(dat_util)[grep('_pc$', names(dat_util))]

temp_util <- dat_util %>%
	arrange(year, service_id) %>%
	select(year, service, !!vars)

years <- 2006:2012
# Format each year into separate table
util_years <- lapply(years, function(y, .data=temp_util, .vars=vars) {
	.temp <- .data %>%
		filter(year==!!y) %>%
		select(service, !!.vars) %>%
		t()

	# Grep col & row names
	services <- .temp[1,]
	payer_types <- sub('_pc$', '', row.names(.temp[-1,]))
	# Cast to tibble
	.temp <- .temp[-1,] %>% as_tibble(rownames=NA)
	# Set col names
	names(.temp) <- services
	# Convert percentages to numeric
	.temp <- mutate_all(.temp, .funs=as.numeric)
	# Add utilization services
	.temp <- mutate(.temp, payer=!!payer_types) %>%
		mutate(payer=case_when(
			payer=='pay_1' ~ 'Medicare',
			payer=='pay_2' ~ 'Medicaid',
			payer=='pay_3' ~ 'Private ins.',
			payer=='pay_4' ~ 'Self-pay',
			payer=='pay_5' ~ 'No charge',
			payer=='pay_6' ~ 'Other')) %>%
		select(payer, everything())

	return(.temp)
})
names(util_years) <- years
```

```{r print util, include=TRUE}
printKable(util_years$`2006`, caption=paste0('Payer types by service utilization, ', 2006))
printKable(util_years$`2007`, caption=paste0('Payer types by service utilization, ', 2007))
printKable(util_years$`2008`, caption=paste0('Payer types by service utilization, ', 2008))
printKable(util_years$`2009`, caption=paste0('Payer types by service utilization, ', 2009))
printKable(util_years$`2010`, caption=paste0('Payer types by service utilization, ', 2010))
printKable(util_years$`2011`, caption=paste0('Payer types by service utilization, ', 2011))
printKable(util_years$`2012`, caption=paste0('Payer types by service utilization, ', 2012))
```


# Share of service utilization by household income quartiles
```{r prep inc}
```
